### PR TITLE
chore: misc. updates

### PR DESCRIPTION
**Pull request by r-park**
chore(package): update dependencies
chore(build): replace existing polyfills with core-js
chore(build): remove gulp as a build dependency
chore(server): replace browser-sync with express
chore(docs): update readme
chore(build): update linters

refactor(TaskService): update methods to align with alpha.16
refactor(AuthService): set initial auth state synchronously

### CODE REVIEW

**Comment by r-park** [comment]
Waiting for angularfire2 alpha.17 to land

**Comment by doovers** [comment]
Why are you setting initial auth state synchronously? And is there a way to modify the firebase ref in TaskService?

**Comment by r-park** [comment]
Initializing auth state synchronously makes it easier to ensure correct auth state is available at startup.

If you need to work directly with the firebase ref, you can inject it into your service/component like so: https://github.com/r-park/todo-angular2-firebase/blob/master/src/core/task/task-service.ts#L13

**Comment by doovers** [comment]
Thanks!

**Pull request merged**
