### PR TITLE
Added support for Anonymous signIn

### PR DESCRIPTION
**Pull request by ykoehler**
The anonymous auth provider must be enabled inside the firebase console for this to work.

### CODE REVIEW

**Comment by sbolel** [comment]
@ykoehler it's failing lint: `src/auth/services/auth-service.ts[30, 41]: trailing whitespace`

**Comment by ykoehler** [comment]
https://github.com/ykoehler/todo-angular2-firebase/tree/support_anonymous

strange my branch is passing...

**Comment by sbolel** [comment]
LGTM 👍

**Comment by r-park** [comment]
Thanks very much @ykoehler and @sbolel 👍 🎉 

(and sorry for the delay)

**Pull request merged**
